/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f411xe.h"


int main(void)
{
   RCC->AHB1ENR |= RCC_AHB1ENR_GPIOCEN;      
    (void)RCC->AHB1ENR;         

    GPIOC->MODER  &= ~GPIO_MODER_MODER13;             
    GPIOC->MODER  |=  GPIO_MODER_MODER13_0;            
    GPIOC->PUPDR  &= ~GPIO_PUPDR_PUPD13;             
    GPIOC->OSPEEDR &= ~GPIO_OSPEEDR_OSPEED13;

    for (;;) 
    {                                  
        GPIOC->BSRR = GPIO_BSRR_BS13;               
        for (volatile uint32_t i = 0; i < 1000000; ++i) {}  
        GPIOC->BSRR = GPIO_BSRR_BR13;          
        for (volatile uint32_t i = 0; i < 1000000; ++i) {}
    }
}
