/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f411xe.h"


int main(void)
{
   RCC->AHB1ENR |= RCC_AHB1ENR_GPIOCEN;      
    (void)RCC->AHB1ENR;         

    GPIOC->MODER  &= ~GPIO_MODER_MODER13;             
    GPIOC->MODER  |=  GPIO_MODER_MODER13_0;            
    GPIOC->PUPDR  &= ~GPIO_PUPDR_PUPD13;             
    GPIOC->OSPEEDR &= ~GPIO_OSPEEDR_OSPEED13;

    RCC->APB2ENR |= RCC_APB2ENR_TIM1EN;

    TIM1->PSC = 15999;      
    TIM1->ARR = 999;       
    TIM1->EGR = TIM_EGR_UG; 
    TIM1->SR = ~TIM_SR_UIF; 
    TIM1->DIER |= TIM_DIER_UIE;

    TIM1->CR1 |= TIM_CR1_CEN;

    NVIC_EnableIRQ(TIM1_UP_TIM10_IRQn);
}


void TIM1_UP_TIM10_IRQHandler(void) 
{
    if (TIM1->SR & TIM_SR_UIF) {
        TIM1->SR &= ~TIM_SR_UIF;  
        GPIOC->ODR ^= GPIO_ODR_OD13; 
    }
}